[package]
name = "globals"
version = "0.1.0"
authors = ["Richard Anaya"]
edition = "2018"
description = "Painless global variables in Rust"
license = "MIT"

[dependencies]
lazy_static = "1.4.0"
hashbrown = "0.6.3"
spin = "0.5"